/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/endusers': RouteRecordInfo<
      '/endusers',
      '/endusers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/professional': RouteRecordInfo<
      '/professional',
      '/professional',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/singlefive': RouteRecordInfo<
      '/singlefive',
      '/singlefive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/singlefour': RouteRecordInfo<
      '/singlefour',
      '/singlefour',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/singlethree': RouteRecordInfo<
      '/singlethree',
      '/singlethree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/singletwo': RouteRecordInfo<
      '/singletwo',
      '/singletwo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/singleuser': RouteRecordInfo<
      '/singleuser',
      '/singleuser',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/endusers.vue': {
      routes:
        | '/endusers'
      views:
        | never
    }
    'src/pages/professional.vue': {
      routes:
        | '/professional'
      views:
        | never
    }
    'src/pages/singlefive.vue': {
      routes:
        | '/singlefive'
      views:
        | never
    }
    'src/pages/singlefour.vue': {
      routes:
        | '/singlefour'
      views:
        | never
    }
    'src/pages/singlethree.vue': {
      routes:
        | '/singlethree'
      views:
        | never
    }
    'src/pages/singletwo.vue': {
      routes:
        | '/singletwo'
      views:
        | never
    }
    'src/pages/singleuser.vue': {
      routes:
        | '/singleuser'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
